services:
  backend:
    build: ./api
    container_name: story-api
    env_file:
      - ./api/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:yeab@db:5432/storydb
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: story-client
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:17
    container_name: story-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yeab
      - POSTGRES_DB=storydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  pgdata: #
    driver: local

networks:
  app-network:
    driver: bridge
